#$ -S /bin/bash
#$ -l virtual_free=3.8G
/mnt/wigclust5/data/safe/kendall/bowtie-0.12.7/bowtie -S -t -n 2 -e 70 -3 0 -5 0 -m 1 --best --strata hg19 /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/SRR054616.fastq /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.sam
/mnt/wigclust5/data/safe/kendall/samtools-0.1.16/samtools view -Sb -o /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.bam /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.sam
/mnt/wigclust5/data/safe/kendall/samtools-0.1.16/samtools sort /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.bam /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.sorted
/mnt/wigclust5/data/safe/kendall/samtools-0.1.16/samtools rmdup -s /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.sorted.bam /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.rmdup.bam
/mnt/wigclust5/data/safe/kendall/samtools-0.1.16/samtools index /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.rmdup.bam
/mnt/wigclust5/data/safe/kendall/samtools-0.1.16/samtools view -o /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.rmdup.sam /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.rmdup.bam
/mnt/wigclust5/data/safe/kendall/Python-2.7.1/python /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/programs/varbin.50k.sam.py /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/mapped/SRR054616.rmdup.sam /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/processed/SRR054616.varbin.50k.txt /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/processed/SRR054616.varbin.50k.stats.txt
/usr/bin/R CMD BATCH /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/processed/SRR054616.cbs.r /mnt/wigclust5/data/safe/kendall/protocols/hg19.50k/processed/SRR054616.cbs.r.out
